@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTMwYWU0MzQ2YjIxNjAwMDQ4NTNkNjUiLCJlbWFpbCI6Imd1ZXN0MTU4MDI0ODY0MzQzMUBtYXRoY293LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpc0dvbGQiOmZhbHNlLCJpYXQiOjE1ODAyNDg2NDN9.YqWzQhfItAYEOgt2w7wOt_RoBIS1xkKFKNpN5Pk35Vw
@baseURL = http://mathcow.herokuapp.com/api

### 
POST {{baseURL}}/cardends 
x-auth-token: {{token}}
content-type: application/json
accept: application/json

{
    "userID": "5e289e950a8de50004d18d9f",
    "points": 10,
    "correctQuestions": 12,
    "wrongQuestions": 5,
    "finishedCards": [{"topicID": "101", "cardID": "103"}]
}


### 
GET {{baseURL}}/questions/101/101
x-auth-token: {{token}}
content-type: application/json