@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTNkNmU2NTU4MWIwODAwMDQ1NmE2M2EiLCJuYW1lIjoiZ3Vlc3QxNTgxMDg0MjYxMTY3IiwiZW1haWwiOiJndWVzdDE1ODEwODQyNjExNjdAbWF0aGNvdy5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNHb2xkIjpmYWxzZSwiaWF0IjoxNTgxMDg0MjYxfQ.kqcVrTBeMonMyFpLj4bZEcsCYbHa_r0yKGnJ84klpNc
@baseURL = http://mathcow.herokuapp.com/api

### 
POST {{baseURL}}/cardends 
x-auth-token: {{token}}
content-type: application/json
accept: application/json

{
    "user_id": "5e3d6e65581b08000456a63a",
    "remainingTime": 0,
    "remainingTime": 12,
    "correctQuestions": 12,   
    "wrongQuestions": 5,
    "finishedCards": [{"topicID": "101", "cardID": "101"}]
}


### 
GET {{baseURL}}/questions/101/101
x-auth-token: {{token}}
content-type: application/json